print('========== segue a baixo o ennuciado ==================')
print(' warnick sai todos os dias  para ir na casa  da thaina porem ele usa o uber \n ele percebeu que  esta  ficando caro de maais continuaa usar o uber por isso resolveu fazer uma conta ')
print('='*12)
dia = int(input(' quantos dias  warnick vai na casa da thainara: '))
km =  float(input(' quantos km e da casa do warnick ate na casa da thaina: '))
valor = ( dia * 10 ) + (km * 0.20)
print(' de acordo com os dados que warnick informou ele gasta por semana  R${} para ir na casa da thaina '.format(valor))
print('='*12)

print('=====================e se eu não quiser ir la ? =================')
print('aluguel de carros ')
dias = int(input('digite quantos dias deseja alugar o carro: '))
km = float(input(' quantos km vocẽ vai andar no carro: '))
preço = (dias * 60 ) + (km * 0.15)
print('de acordo com os dados o total apaga e de R${:.2f}'.format(preço))